// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcf8BilP8p6tpqR43TmHGV0p21cJizVKA',
    appId: '1:531009455731:web:ccaeeb00ee41f9556ecc06',
    messagingSenderId: '531009455731',
    projectId: 'preganancy-tracker',
    authDomain: 'preganancy-tracker.firebaseapp.com',
    storageBucket: 'preganancy-tracker.firebasestorage.app',
    measurementId: 'G-K8EB333Q81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXi75ConmqvhxQxqmANg0zrlRnY5CDusI',
    appId: '1:531009455731:android:b5417e22d44d3d3c6ecc06',
    messagingSenderId: '531009455731',
    projectId: 'preganancy-tracker',
    storageBucket: 'preganancy-tracker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcf8BilP8p6tpqR43TmHGV0p21cJizVKA',
    appId: '1:531009455731:web:6f8d30cee548655d6ecc06',
    messagingSenderId: '531009455731',
    projectId: 'preganancy-tracker',
    authDomain: 'preganancy-tracker.firebaseapp.com',
    storageBucket: 'preganancy-tracker.firebasestorage.app',
    measurementId: 'G-VRJZ8YBQ7E',
  );
}
